#!/usr/bin/env bash
# Copy KaTeX + JSXGraph into frontend/public/vendor for offline / pre-download use.
# Daily refresh: re-run this after `npm ci` (or cron it). Bundled Vite imports still work without this.
set -euo pipefail
cd "$(dirname "$0")/.."

ROOT_NM=node_modules
if [[ ! -d "$ROOT_NM/katex" ]]; then
  echo "missing node_modules/katex — run npm ci first" >&2
  exit 1
fi

DEST=frontend/public/vendor
mkdir -p "$DEST/katex/fonts" "$DEST/jsxgraph"

# KaTeX CSS + JS + fonts (self-contained under /vendor/katex/)
cp -f "$ROOT_NM/katex/dist/katex.min.css" "$DEST/katex/"
cp -f "$ROOT_NM/katex/dist/katex.min.js" "$DEST/katex/"
cp -f "$ROOT_NM/katex/dist/katex.js" "$DEST/katex/" 2>/dev/null || true
cp -Rf "$ROOT_NM/katex/dist/fonts/." "$DEST/katex/fonts/"

# JSXGraph core + CSS for prototype boards / plain HTML sketches
cp -f "$ROOT_NM/jsxgraph/distrib/jsxgraph.css" "$DEST/jsxgraph/"
cp -f "$ROOT_NM/jsxgraph/distrib/jsxgraphcore.js" "$DEST/jsxgraph/"

cat > "$DEST/README.md" << 'EOF'
# Vendored math assets

Generated by `scripts/vendor-math-assets.sh`.

| Path | Use |
| --- | --- |
| `katex/` | Framework default for wiki math (`$…$` and ` ```eq `). Also loadable from plain HTML. |
| `jsxgraph/` | Interactive plots for prototyping (not TeX). |

## Preferred path (this repo)

`npm ci` installs packages; Vite bundles KaTeX CSS/JS via `import 'katex/dist/katex.min.css'` and `katex` in `frontend/src/site/katexRender.ts`. You do **not** need `/vendor` for the site to run.

## Offline / plain HTML / daily refresh

```bash
npm ci
./scripts/vendor-math-assets.sh
```

Then in a scratch HTML file:

```html
<link rel="stylesheet" href="/vendor/katex/katex.min.css" />
<script defer src="/vendor/katex/katex.min.js"></script>
<link rel="stylesheet" href="/vendor/jsxgraph/jsxgraph.css" />
<script src="/vendor/jsxgraph/jsxgraphcore.js"></script>
```

Re-run the script whenever you want a fresh copy from `node_modules` (including a daily cron if you like).
EOF

echo "vendored → $DEST"
ls -la "$DEST/katex" | head -8
ls -la "$DEST/jsxgraph"
